services:

  start-vectormind:
    labels:
      local.service: start-vectormind
    image: ubuntu:22.04
    ports:
      - 9090:9090
      - 8080:8080
    environment:
      TARGETOS: linux
      TARGETARCH: arm64    

      REDIS_INDEX_NAME: vectormind_index
      REDIS_ADDRESS: redis-test-server:6379
      REDIS_PASSWORD: ""

      MCP_HTTP_PORT: 9090
      API_REST_PORT: 8080

    volumes:
      - ./builds:/builds      
    command:       
      - /bin/sh
      - -c
      - |  
        apt-get update && apt-get install -y wget
        echo "🚀 Starting the service locally on port 8080"
        chmod +x ./builds/vectormind-$${TARGETOS}-$${TARGETARCH}
        ./builds/vectormind-$${TARGETOS}-$${TARGETARCH}

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 40s

    models:
      embedding-model:
        endpoint_var: MODEL_RUNNER_BASE_URL
        model_var: EMBEDDING_MODEL
